UPDATE `xidb`.`npc_list` SET `content_tag`='TOAU' WHERE  `npcid`=17793129;
UPDATE `xidb`.`npc_list` SET `content_tag`='TOAU' WHERE  `npcid`=17793129;
UPDATE `xidb`.`npc_list` SET `content_tag`='TOAU' WHERE  `npcid`=17793130;
UPDATE `xidb`.`npc_list` SET `content_tag`='TOAU' WHERE  `npcid`=17797251;
UPDATE `xidb`.`npc_list` SET `content_tag`='TOAU' WHERE  `npcid`=17797252;
UPDATE `mob_pools` SET `poolid`=5975, `name`='maximilian', `packet_name`='Leorax', `speciesid`=295, `mJob`=1, `sJob`=13, `cmbSkill`=3, `cmbDelay`=240, `cmbDmgMult`=100, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=0, `namevis`=0, `roamflag`=0, `skill_list_id`=5005, `resist_id`=149, `modelSize`=1, `modelHitboxSize`=17 WHERE `poolid`=5975;
UPDATE `mob_pools` SET `poolid`=5910, `name`='valaineral', `packet_name`='Adrius', `speciesid`=293, `mJob`=7, `sJob`=1, `cmbSkill`=3, `cmbDelay`=240, `cmbDmgMult`=100, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=322, `namevis`=0, `roamflag`=0, `skill_list_id`=5005, `resist_id`=145, `modelSize`=1, `modelHitboxSize`=12 WHERE `poolid`=5910;
UPDATE `mob_pools` SET `poolid`=5964, `name`='lhe_lhangavo', `packet_name`='Danica', `speciesid`=293, `mJob`=2, `sJob`=1, `cmbSkill`=1, `cmbDelay`=480, `cmbDmgMult`=100, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=0, `namevis`=0, `roamflag`=0, `skill_list_id`=5010, `resist_id`=145, `modelSize`=1, `modelHitboxSize`=17 WHERE `poolid`=5964;
UPDATE `mob_pools` SET `poolid`=5917, `name`='iron_eater', `packet_name`='Catatonic', `speciesid`=294, `mJob`=1, `sJob`=12, `cmbSkill`=6, `cmbDelay`=480, `cmbDmgMult`=220, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=0, `namevis`=0, `roamflag`=0, `skill_list_id`=5020, `resist_id`=146, `modelSize`=0, `modelHitboxSize`=20 WHERE `poolid`=5917;
UPDATE `mob_pools` SET `poolid`=5977, `name`='robel-akbel', `packet_name`='Gandus', `speciesid`=297, `mJob`=4, `sJob`=15, `cmbSkill`=3, `cmbDelay`=240, `cmbDmgMult`=100, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=390, `namevis`=0, `roamflag`=0, `skill_list_id`=1092, `resist_id`=153, `modelSize`=2, `modelHitboxSize`=17 WHERE `poolid`=5977;
UPDATE `mob_pools` SET `poolid`=5955, `name`='apururu_uc', `packet_name`='Xania', `speciesid`=297, `mJob`=3, `sJob`=5, `cmbSkill`=3, `cmbDelay`=240, `cmbDmgMult`=100, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=367, `namevis`=0, `roamflag`=0, `skill_list_id`=0, `resist_id`=153, `modelSize`=0, `modelHitboxSize`=12 WHERE `poolid`=5955;
UPDATE `mob_pools` SET `poolid`=6005, `name`='ayame_uc', `packet_name`='Leila', `speciesid`=295, `mJob`=12, `sJob`=1, `cmbSkill`=10, `cmbDelay`=440, `cmbDmgMult`=210, `behavior`=0, `aggro`=0, `true_detection`=0, `links`=0, `mobType`=0, `immunity`=0, `name_prefix`=32, `flag`=0, `entityFlags`=3, `animationsub`=0, `hasSpellScript`=0, `spellList`=0, `namevis`=0, `roamflag`=0, `skill_list_id`=5001, `resist_id`=149, `modelSize`=NULL, `modelHitboxSize`=NULL WHERE `poolid`=6005;
INSERT INTO `mob_skill_lists` (`skill_list_name`, `skill_list_id`, `mob_skill_id`) VALUES ('G_KATANA_1', 5001, 145);
INSERT INTO `mob_skill_lists` (`skill_list_name`, `skill_list_id`, `mob_skill_id`) VALUES ('1H_SWORD_3', 5005, 34);
INSERT INTO `mob_skill_lists` (`skill_list_name`, `skill_list_id`, `mob_skill_id`) VALUES ('H2H_1', 5010, 2);
INSERT INTO `mob_skill_lists` (`skill_list_name`, `skill_list_id`, `mob_skill_id`) VALUES ('CAT_3', 5020, 81);
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=640;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=641;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=642;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=643;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=644;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=645;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=646;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=647;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=678;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=685;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=736;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=737;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=738;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=739;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=688;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=689;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=690;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=691;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=692;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=693;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=694;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=695;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=696;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=697;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=698;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=699;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=700;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=701;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=702;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=703;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1446;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1464;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=857;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=858;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=859;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=860;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=861;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=862;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=863;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=871;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=874;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1116;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1293;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1516;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1591;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=1628;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2121;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2123;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2139;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2151;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2169;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2428;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2512;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2518;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2613;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2619;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2750;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2655;
INSERT INTO `mob_droplist` (`dropId`, `dropType`, `groupId`, `groupRate`, `itemId`, `itemRate`) VALUES (2745, 0, 0, 1000, 4994, 150);
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=498;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=496;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=596;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=501;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=2758;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=507;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=508;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=510;
UPDATE `xidb`.`item_basic` SET `stackSize`=12 WHERE  `itemid`=511;
UPDATE `xidb`.`zone_settings` SET `zoneip`='73.62.92.12' WHERE `zoneid`>= '0'
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=977;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=955;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=1005;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=917;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=910;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=975;
UPDATE `xidb`.`spell_list` SET `recastTime`=5000 WHERE  `spellid`=964;
